#!/bin/bash
read -p "Qual ambiente deseja pegar os logs | UAT digite fqa ou PROD digite prd  " ambiente
changeEnv.sh $ambiente
usuario=$(cmd.exe /c echo %homepath% 2> /dev/null | sed 's/\\/\//g' | awk '{ sub("\r$", ""); print }')
disco="/mnt/c"
destino="$disco$usuario/Downloads/portabilidade/"

#Se o diretorio nao existir ele sera criado
if [ ! -d "$destino" ]; then
	mkdir -p $destino
else
	#Se já existir seu conteúdo será removido
	rm -rf $destino*
fi

#Verifica se o 7zip está instalado senao estiver instala
if ! command -v "7z" &>/dev/null; then
    echo "Instalando '7zip'..."
        sudo apt update
        sudo apt install -y "p7zip-full"
fi

if [ $ambiente == "fqa"  ]; then 
	ambiente=uat
fi

echo "Copiando arquivos"
kubectl cp s-$ambiente/$(getPods.sh consumer-events-portability $ambiente | grep -i running | awk '{print $2}'):/tmp/kafka-portability/ $destino > /dev/null

echo "Apagando arquivos vazios"
find $destino -type f -size 0 -exec rm {} \;

zip="$(sed 's/portabilidade\///g' <<< $destino)portabilidade.zip"

#Se o arquivo compactado já existir ele será removido 
if [ -f "$zip" ]; then
	rm -rf $zip 
fi

echo "Compactando"
zip="$(sed 's/portabilidade\///g' <<< $destino)portabilidade.zip"
7z a -tzip -mx=5 $zip $destino
