#!/bin/bash
token=$(cat $HOME/token)
tokenfull="Authorization: Bearer $token"

teste=( $(ls $HOME/gitlab/pmid/nio) )
tags=()

i=0
while [ $i -lt ${#teste[@]} ]
do
cd $HOME/gitlab/pmid/nio/${teste[$i]} 
#echo ${teste[$i]} >> ~/scripts/gittagteste2
#git tag --sort=-v:refname | grep -E '^[0-9.]+$' | head -n 10  >> ~/scripts/gittagteste2
#tags=( $(git tag --sort=-v:refname | grep -E '^[0-9.]+$' | head -n 1) )
tags+=( "$(git tag --sort=-v:refname | grep -E '^[0-9.]+$' | head -n 1)" ) 
echo ${teste[$i]}
echo ${tags[$i]}
i=$(( $i + 1 ))
done