#!/bin/bash
servico=$1
token=SEUTOKENAQUI

versao=$(checkVersion.sh $servico $2 | awk -F ' ' '{print $2}')
nome=( $(curl -s --header "Authorization: Bearer $token" -X GET https://gitlab.engdb.com.br/api/v4/projects?search=$servico | jq '.[].name' |  sed 's/"//g' ) )
names=( $(curl -s --header "Authorization: Bearer $token" -X GET https://gitlab.engdb.com.br/api/v4/projects?search=$servico | jq '.[].path_with_namespace' |  sed 's/"//g' | awk -F/ '{print $1}' ) ) 
names2=( $(curl -s --header "Authorization: Bearer $token" -X GET https://gitlab.engdb.com.br/api/v4/projects?search=$servico | jq '.[].path_with_namespace' |  sed 's/"//g' | awk -F/ '{print $2}' ) ) 
ids=( $(curl -s --header "Authorization: Bearer $token" -X GET https://gitlab.engdb.com.br/api/v4/projects?search=$servico | jq '.[].id' ) ) 

i=0
while [ $i -lt ${#names[@]} ]
do
    if [ ${servicos[$cont]} == ${nome[$i]} ]; then 
        if [[ ${names2[$i]} = nio ]]; then
        versao=$(checkVersion.sh ${servicos[$cont]} $2 | awk -F ' ' '{print $2}')
        elif [[ ${names2[$i]} = ejb ]]; then 
        versao=$(checkVersion.sh ${servicos[$cont]} e-$2 | awk -F ' ' '{print $2}')
        elif [[ ${names2[$i]} = brms ]]; then
        versao=$(checkVersion.sh ${servicos[$cont]} s-$2 | awk -F ' ' '{print $2}')
        fi
    fi
projeto=$(echo ${ids[$i]})
i=$(( $i + 1 ))
done


ver=( $(curl -s  --header "Authorization: Bearer $token" -X GET https://gitlab.engdb.com.br/api/v4/projects/$projeto/pipelines | jq '.[].ref' |  sed 's/"//g') )
pipeline=( $(curl -s  --header "Authorization: Bearer $token" -X GET https://gitlab.engdb.com.br/api/v4/projects/$projeto/pipelines | jq '.[].web_url' |   sed 's/"//g') )

int=0
while [ "$versao" != "${ver[$int]}" ]
  do
  int=$(( $int + 1 ))
done
echo  "Serviço: $servico | Versão: $versao | Pipeline: ${pipeline[$int]}" 
