#!/bin/bash
token=$(cat $HOME/token)
tokenfull="Authorization: Bearer $token"
servico=orch-r-customer-access-v1
versao=1.12.0.46

id=$(curl -s --header "$tokenfull" -X GET https://gitlab.engdb.com.br/api/v4/projects?search=$servico | jq '.[].id' )
pipeline=$(curl -s --header "$tokenfull" -X GET https://gitlab.engdb.com.br/api/v4/projects/$id/pipelines?per_page=300 | jq --arg versao "$versao" '.[] | select(.ref == $versao) | .id' )
job=$(curl -s --request GET --header "$tokenfull" https://gitlab.engdb.com.br/api/v4/projects/$id/pipelines/$pipeline/jobs | jq '.[] | select(.name == "deploy_st") | .id')
curl -s --request POST --header "$tokenfull" "https://gitlab.engdb.com.br/api/v4/projects/$id/jobs/$job/play" > /dev/null 