#!/bin/bash
#Script que apaga um serviço instalado
namespace=$(echo "$2" | awk '{print tolower($0)}')

if [ -z $namespace ]; then
	if [ -f  $HOME/namespace.txt ]; then
		namespace=$(< $HOME/namespace.txt)
	else
	echo "Ambiente nao informado e arquivo $HOME/namespace.txt nao existe"
	exit 1
	fi
fi

servico=$(echo "$1" | awk '{print tolower($0)}')

kubectl delete deployment $servico --namespace $namespace
